// <auto-generated />
using System;
using Identificacao.Infra.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Identificacao.Infra.Migrations
{
    [DbContext(typeof(DadosContexto))]
    [Migration("20210115182948_criando_banco")]
    partial class criando_banco
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Identificacao.Dominio.Entidades.Empresas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int");

                    b.Property<Guid>("AccessToken")
                        .HasColumnName("ACCESS_TOKEN")
                        .HasColumnType("CHAR(36)")
                        .HasMaxLength(36);

                    b.Property<string>("Bairro")
                        .HasColumnName("BAIRRO")
                        .HasColumnType("VARCHAR(60)")
                        .HasMaxLength(60);

                    b.Property<string>("Cep")
                        .HasColumnName("CEP")
                        .HasColumnType("VARCHAR(8)")
                        .HasMaxLength(8);

                    b.Property<string>("Cidade")
                        .HasColumnName("CIDADE")
                        .HasColumnType("VARCHAR(60)")
                        .HasMaxLength(60);

                    b.Property<string>("Cnpj")
                        .HasColumnName("CNPJ")
                        .HasColumnType("VARCHAR(18)")
                        .HasMaxLength(18);

                    b.Property<string>("CodCidade")
                        .HasColumnName("COD_CIDADE")
                        .HasColumnType("VARCHAR(7)")
                        .HasMaxLength(7);

                    b.Property<string>("Complemento")
                        .HasColumnName("COMPLEMENTO")
                        .HasColumnType("VARCHAR(60)")
                        .HasMaxLength(60);

                    b.Property<string>("InscricaoEstadual")
                        .HasColumnName("INSCRICAO_ESTADUAL")
                        .HasColumnType("VARCHAR(15)")
                        .HasMaxLength(15);

                    b.Property<string>("Logradouro")
                        .HasColumnName("LOGRADOURO")
                        .HasColumnType("VARCHAR(60)")
                        .HasMaxLength(60);

                    b.Property<string>("Numero")
                        .HasColumnName("NUMERO")
                        .HasColumnType("VARCHAR(60)")
                        .HasMaxLength(60);

                    b.Property<string>("RazaoSocial")
                        .HasColumnName("RAZAO_SOCIAL")
                        .HasColumnType("VARCHAR(60)")
                        .HasMaxLength(60);

                    b.Property<string>("Uf")
                        .HasColumnName("UF")
                        .HasColumnType("VARCHAR(2)")
                        .HasMaxLength(2);

                    b.HasKey("Id");

                    b.ToTable("EMPRESAS");
                });

            modelBuilder.Entity("Identificacao.Dominio.Entidades.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID_USUARIO")
                        .HasColumnType("int");

                    b.Property<string>("Celular")
                        .HasColumnName("CELULAR")
                        .HasColumnType("varchar(14)")
                        .HasMaxLength(14);

                    b.Property<string>("Email")
                        .HasColumnName("EMAIL")
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150);

                    b.Property<int>("IdEmpresa")
                        .HasColumnName("ID_EMPRESA")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnName("NOME")
                        .HasColumnType("varchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("Senha")
                        .HasColumnName("SENHA")
                        .HasColumnType("varchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("Status")
                        .HasColumnName("STATUS")
                        .HasColumnType("char(1)")
                        .HasMaxLength(1);

                    b.Property<string>("Supervisor")
                        .HasColumnName("SUPERVISOR")
                        .HasColumnType("char(1)")
                        .HasMaxLength(1);

                    b.Property<string>("UltimoNome")
                        .HasColumnName("ULTIMO_NOME")
                        .HasColumnType("varchar(60)")
                        .HasMaxLength(60);

                    b.HasKey("Id");

                    b.ToTable("USUARIOS");
                });
#pragma warning restore 612, 618
        }
    }
}
